# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-docker-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-docker-data
  template:
    metadata:
      labels:
        app: test-docker-data
    spec:
      containers:
      - name: test-docker-data
        image: ramugadde84/test-docker:1.0
