apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: my-spring-app-config
        - name: secrets-volume
          secret:
            secretName: my-spring-app-secret
        - name: heap-dumps
          emptyDir: {}
        - name: tls-secret
          secret:
            secretName: my-tls-secret
      containers:
        - name: spring-boot-kubernetes-test1
          image: ramugadde84/test-docker-spring-boot:4.0
          volumeMounts:
            - name: heap-dumps
              mountPath: /heapdumps
            - name: config-volume
              mountPath: /config
            - name: secrets-volume
              mountPath: /secrets
            - name: tls-secret
              mountPath: /tls
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /config/application.yml
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-spring-app-secret
                  key: database-password
          resources:
            limits:
              memory: "1000Mi"
            requests:
              memory: "500Mi"